### ISSUE TITLE
Button Block ist not available with ALPS-Wordpress Theme

### ISSUE THREAD

**Issue by cdbieling** [adventistchurch/alps-gutenberg-blocks#19] opened 2020-02-02 14:31 UTC
Using ALPS Wordpress Theme v.3.0.32, many Wordpress-Blocks are not available. I don't know, why they are blocked with the ALPS-Theme, but however, in this issue, i report, that in my Theme v. 3.0.32, there is no Button-Block.  

I am using latest alps-Gutenberg-blocks 1.3.5

**Comment by designerbrent** [comment] 2020-03-11 12:28
This is a duplicate of https://github.com/adventistchurch/alps-wordpress/issues/440

**Closed as completed by designerbrent** 2020-03-11 12:28 UTC

**Comment by designerbrent** [comment] 2020-03-11 12:48
I closed this too quick, thinking it was another issue, without giving a full answer. So let me try here: 

There are some sites that are experiencing this problem of the button not showing. I'm looking into it, and will be tracking it on the issue referenced above on the `ALPS for Wordpress` theme repo, not this plugin. 

The reason that we have blocked other blocks from being available is that we chose to make sure the code they output is supported by the theme. If there are other blocks that are still blocked, please open individual issues for each one so that we can be sure they output correctly and look good in the theme.
